### ISSUE TITLE
Example usage for VC++/Windows

### ISSUE THREAD

**Issue by afabri** [leokollersacht/pompeiu_hausdorff#3]
When compiled and executed with VC++  I get a negative number for `max_vertices`  in [`main.cpp:L126`](https://github.com/leokollersacht/pompeiu_hausdorff/blob/9b8880df975e44655406a2f55904e6a7610c1846/main.cpp#L126)  for the example usage you give.  This gives a segfault when constructing a matrix later. `VA.rows()`  is 13680 under the debugger.

**Comment by leokollersacht** [comment]
Hi Andreas,

I made a little change that should solve the problem (it wasn't happening in my setup). Can you please try to run the code with the change I made?

Thank you,
Leonardo.
